import { afterEach, describe, expect, it, vi } from 'vitest';
import { extractText, extractJson, scholarPaperLimit } from '../server/gemini';

/**
 * Interactions responses have no `.text` — output lives in a `model_output`
 * step, and the SDK's autogenerated types are too weak to trust a single field
 * name. These fixtures pin the shapes the live API has actually returned, so an
 * SDK upgrade that moves the text surfaces here instead of as empty blog posts.
 */
describe('extractText', () => {
  it('reads the canonical model_output step', () => {
    expect(
      extractText({
        steps: [
          { type: 'thought', content: [{ text: 'let me think about this' }] },
          { type: 'model_output', content: [{ text: 'the answer' }] },
        ],
      })
    ).toBe('the answer');
  });

  it('skips thought steps wherever they appear', () => {
    expect(
      extractText({
        steps: [
          { type: 'model_output', content: [{ text: 'a' }] },
          { type: 'thought', content: [{ text: 'IGNORED' }] },
          { type: 'model_output', content: [{ text: 'b' }] },
        ],
      })
    ).toBe('ab');
  });

  it('concatenates multiple content items in order', () => {
    expect(
      extractText({
        steps: [{ type: 'model_output', content: [{ text: 'one ' }, { text: 'two' }] }],
      })
    ).toBe('one two');
  });

  it.each(['content', 'parts', 'output', 'output_text', 'value'])(
    'harvests text nested under %s',
    key => {
      expect(extractText({ steps: [{ type: 'model_output', [key]: [{ text: 'found' }] }] })).toBe(
        'found'
      );
    }
  );

  it('accepts a bare string where an object is expected', () => {
    expect(extractText({ steps: [{ type: 'model_output', content: 'plain' }] })).toBe('plain');
  });

  it('falls back to top-level output_text when there are no steps', () => {
    expect(extractText({ output_text: 'legacy shape' })).toBe('legacy shape');
  });

  it('trims surrounding whitespace', () => {
    expect(extractText({ steps: [{ type: 'model_output', content: [{ text: '  hi\n' }] }] })).toBe(
      'hi'
    );
  });

  it.each([[{}], [{ steps: [] }], [null], [undefined], [{ steps: [{ type: 'thought' }] }]])(
    'returns an empty string for %j rather than throwing',
    input => {
      expect(extractText(input)).toBe('');
    }
  );
});

const wrap = (text: string) => ({ steps: [{ type: 'model_output', content: [{ text }] }] });

describe('extractJson', () => {
  it('parses clean JSON', () => {
    expect(extractJson(wrap('{"blogTitle":"Hi","slides":[]}'), null)).toEqual({
      blogTitle: 'Hi',
      slides: [],
    });
  });

  it('strips a markdown fence the model added anyway', () => {
    expect(extractJson(wrap('```json\n{"ok":true}\n```'), null)).toEqual({ ok: true });
  });

  it('returns the fallback for empty output', () => {
    expect(extractJson(wrap(''), { fallback: true })).toEqual({ fallback: true });
  });

  it('returns the fallback for the File Search array corruption', () => {
    // Observed live: with File Search attached, the citation-insertion pass
    // rewrites the `[` that opens an array. Must degrade, never throw.
    const corrupted = '{"title":"Overfitting","points":.", "x": 1}';
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(extractJson(wrap(corrupted), { fallback: true })).toEqual({ fallback: true });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });

  it('returns the fallback for truncated output', () => {
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(extractJson(wrap('{"blogContent":"half a sen'), null)).toBeNull();
    spy.mockRestore();
  });
});

/**
 * How many publications one scholar search asks for.
 *
 * A single grounded generation degrades rather than fails when asked for too
 * much — invented years, merged titles toward the tail — so the ceiling is
 * enforced rather than left to whoever passes the parameter.
 */
describe('scholarPaperLimit', () => {
  afterEach(() => vi.unstubAllEnvs());

  it('defaults to twenty', () => {
    vi.stubEnv('SCHOLAR_PAPER_LIMIT', '');
    expect(scholarPaperLimit()).toBe(20);
  });

  it('takes the environment default when nothing is requested', () => {
    vi.stubEnv('SCHOLAR_PAPER_LIMIT', '35');
    expect(scholarPaperLimit()).toBe(35);
  });

  it('lets a request override the default', () => {
    vi.stubEnv('SCHOLAR_PAPER_LIMIT', '20');
    expect(scholarPaperLimit(8)).toBe(8);
  });

  it('caps at fifty, past which the answer stops being trustworthy', () => {
    expect(scholarPaperLimit(500)).toBe(50);
    vi.stubEnv('SCHOLAR_PAPER_LIMIT', '9999');
    expect(scholarPaperLimit()).toBe(50);
  });

  it('never returns less than one, whatever it is handed', () => {
    for (const bad of [0, -5, NaN, undefined]) {
      expect(scholarPaperLimit(bad as number)).toBeGreaterThanOrEqual(1);
    }
  });

  it('floors a fractional request rather than passing it to the prompt', () => {
    expect(scholarPaperLimit(12.7)).toBe(12);
  });

  it('is read at call time, so it can change without a restart', () => {
    vi.stubEnv('SCHOLAR_PAPER_LIMIT', '15');
    expect(scholarPaperLimit()).toBe(15);
    vi.stubEnv('SCHOLAR_PAPER_LIMIT', '25');
    expect(scholarPaperLimit()).toBe(25);
  });
});
