import { describe, expect, it, vi } from 'vitest';
import { extractText, extractJson } from '../server/gemini';

/**
 * Interactions responses have no `.text` — output lives in a `model_output`
 * step, and the SDK's autogenerated types are too weak to trust a single field
 * name. These fixtures pin the shapes the live API has actually returned, so an
 * SDK upgrade that moves the text surfaces here instead of as empty blog posts.
 */
describe('extractText', () => {
  it('reads the canonical model_output step', () => {
    expect(
      extractText({
        steps: [
          { type: 'thought', content: [{ text: 'let me think about this' }] },
          { type: 'model_output', content: [{ text: 'the answer' }] },
        ],
      })
    ).toBe('the answer');
  });

  it('skips thought steps wherever they appear', () => {
    expect(
      extractText({
        steps: [
          { type: 'model_output', content: [{ text: 'a' }] },
          { type: 'thought', content: [{ text: 'IGNORED' }] },
          { type: 'model_output', content: [{ text: 'b' }] },
        ],
      })
    ).toBe('ab');
  });

  it('concatenates multiple content items in order', () => {
    expect(
      extractText({
        steps: [{ type: 'model_output', content: [{ text: 'one ' }, { text: 'two' }] }],
      })
    ).toBe('one two');
  });

  it.each(['content', 'parts', 'output', 'output_text', 'value'])(
    'harvests text nested under %s',
    key => {
      expect(extractText({ steps: [{ type: 'model_output', [key]: [{ text: 'found' }] }] })).toBe(
        'found'
      );
    }
  );

  it('accepts a bare string where an object is expected', () => {
    expect(extractText({ steps: [{ type: 'model_output', content: 'plain' }] })).toBe('plain');
  });

  it('falls back to top-level output_text when there are no steps', () => {
    expect(extractText({ output_text: 'legacy shape' })).toBe('legacy shape');
  });

  it('trims surrounding whitespace', () => {
    expect(extractText({ steps: [{ type: 'model_output', content: [{ text: '  hi\n' }] }] })).toBe(
      'hi'
    );
  });

  it.each([[{}], [{ steps: [] }], [null], [undefined], [{ steps: [{ type: 'thought' }] }]])(
    'returns an empty string for %j rather than throwing',
    input => {
      expect(extractText(input)).toBe('');
    }
  );
});

const wrap = (text: string) => ({ steps: [{ type: 'model_output', content: [{ text }] }] });

describe('extractJson', () => {
  it('parses clean JSON', () => {
    expect(extractJson(wrap('{"blogTitle":"Hi","slides":[]}'), null)).toEqual({
      blogTitle: 'Hi',
      slides: [],
    });
  });

  it('strips a markdown fence the model added anyway', () => {
    expect(extractJson(wrap('```json\n{"ok":true}\n```'), null)).toEqual({ ok: true });
  });

  it('returns the fallback for empty output', () => {
    expect(extractJson(wrap(''), { fallback: true })).toEqual({ fallback: true });
  });

  it('returns the fallback for the File Search array corruption', () => {
    // Observed live: with File Search attached, the citation-insertion pass
    // rewrites the `[` that opens an array. Must degrade, never throw.
    const corrupted = '{"title":"Overfitting","points":.", "x": 1}';
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(extractJson(wrap(corrupted), { fallback: true })).toEqual({ fallback: true });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });

  it('returns the fallback for truncated output', () => {
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(extractJson(wrap('{"blogContent":"half a sen'), null)).toBeNull();
    spy.mockRestore();
  });
});
