import { GoogleGenAI } from '@google/genai';
import { FlashCard, Paper, QuizQuestion, Slide } from '../types';

/** Verified available 2026-09-05 by scripts/spike-phase0.mjs. */
export const MODELS = {
  text: 'gemini-3.8-flash',
  image: 'gemini-3.1-flash-image',
  tts: 'gemini-3.1-flash-tts-preview',
  embedding: 'gemini-embedding-2',
} as const;

/**
 * The model for calls that attach **no tools**.
 *
 * Grounding — `google_search`, `url_context`, `file_search` — is a Gemini
 * feature. Anything that depends on it must stay on `MODELS.text`: a scholar
 * search without grounding does not fail, it invents a plausible publication
 * list, which is the precise failure the citation rules here exist to prevent.
 *
 * A growing share of calls need no tools at all, because retrieval moved to
 * Postgres and the passages arrive in the prompt: advisor answers, panel
 * synthesis, cross-library chat and the structuring pass. Those are free to run
 * on something cheaper or open-weights.
 *
 *   PLAIN_TEXT_MODEL=gemma-3-27b-it
 *
 * Verify a candidate before trusting it — `npm run spike:models` reports which
 * models exist and, more importantly, which silently ignore an attached tool
 * rather than refusing it.
 */
export const plainModel = (): string => process.env.PLAIN_TEXT_MODEL || MODELS.text;

let _ai: GoogleGenAI | undefined;
export const ai = (): GoogleGenAI => {
  if (!_ai) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY is not set on the server.');
    // File Search is unavailable on Vertex (spike finding F1/R5), so the
    // Developer API is used in every environment.
    _ai = new GoogleGenAI({ apiKey });
  }
  return _ai;
};

export async function retryWithBackoff<T>(fn: () => Promise<T>, retries = 3, delay = 2000): Promise<T> {
  try {
    return await fn();
  } catch (error: any) {
    const isRateLimit =
      error.status === 429 ||
      error.code === 429 ||
      error.message?.includes('429') ||
      error.message?.includes('quota') ||
      error.message?.includes('RESOURCE_EXHAUSTED');
    if (retries > 0 && isRateLimit) {
      console.warn(`Rate limit hit. Retrying in ${delay}ms...`);
      await new Promise(resolve => setTimeout(resolve, delay));
      return retryWithBackoff(fn, retries - 1, delay * 2);
    }
    throw error;
  }
}

/**
 * Interaction responses expose no `.text`; output lives in a `model_output`
 * step alongside a `thought` step (spike finding R10/O3). The SDK's Interactions
 * types are autogenerated and weakly typed (R13), so this walks defensively
 * rather than trusting a single field name.
 */
export const extractText = (interaction: any): string => {
  const steps: any[] = interaction?.steps ?? [];
  const chunks: string[] = [];

  const harvest = (node: any): void => {
    if (node == null) return;
    if (typeof node === 'string') { chunks.push(node); return; }
    if (Array.isArray(node)) { node.forEach(harvest); return; }
    if (typeof node !== 'object') return;
    if (typeof node.text === 'string') { chunks.push(node.text); return; }
    for (const key of ['content', 'parts', 'output', 'output_text', 'value']) {
      if (node[key] != null) harvest(node[key]);
    }
  };

  for (const step of steps) {
    if (step?.type === 'thought') continue;
    harvest(step);
  }
  if (!chunks.length) {
    for (const key of ['output_text', 'text']) {
      if (typeof interaction?.[key] === 'string') chunks.push(interaction[key]);
    }
  }
  return chunks.join('').trim();
};

export const extractJson = <T,>(interaction: any, fallback: T): T => {
  const text = extractText(interaction);
  if (!text) return fallback;
  try {
    return JSON.parse(text) as T;
  } catch {
    // response_format enforces structure, but a stray fence costs nothing to strip.
    const cleaned = text.replace(/```json/g, '').replace(/```/g, '').trim();
    try {
      return JSON.parse(cleaned) as T;
    } catch (e: any) {
      console.error(
        `[extractJson] unparseable output: ${text.length} chars, ` +
        `ends with ${JSON.stringify(text.slice(-60))}, error: ${e?.message}`
      );
      return fallback;
    }
  }
};

// The SDK types `response_format`/`tools` loosely; these keep call sites readable.
type Tool = Record<string, unknown>;
interface AskOptions {
  input: string;
  schema?: Record<string, unknown>;
  tools?: Tool[];
  model?: string;
}

export const ask = async (opts: AskOptions): Promise<any> => {
  const params: Record<string, unknown> = {
    model: opts.model ?? MODELS.text,
    input: opts.input,
  };
  if (opts.schema) params.response_format = opts.schema;
  if (opts.tools?.length) params.tools = opts.tools;
  return retryWithBackoff(() => (ai().interactions as any).create(params));
};

export const googleSearchTool = (): Tool => ({ type: 'google_search' });
export const urlContextTool = (): Tool => ({ type: 'url_context' });
export const fileSearchTool = (storeNames: string[], topK = 8): Tool => ({
  type: 'file_search',
  file_search_store_names: storeNames,
  top_k: topK,
});

// --- Schemas ---------------------------------------------------------------
// response_format takes an inline JSON-Schema-shaped object (spike finding R9/O2),
// which replaces the prompt-embedded schemas and fence-stripping of the old client.
const PAPER_FIELDS = {
  title: { type: 'string' },
  year: { type: 'string' },
  authors: { type: 'array', items: { type: 'string' } },
  citationCount: { type: 'string' },
  summary: { type: 'string' },
};

const SCHOLAR_SCHEMA = {
  type: 'object',
  properties: {
    name: { type: 'string' },
    affiliation: { type: 'string' },
    topics: { type: 'array', items: { type: 'string' } },
    papers: {
      type: 'array',
      items: { type: 'object', properties: PAPER_FIELDS, required: ['title'] },
    },
  },
  required: ['name', 'affiliation', 'topics', 'papers'],
};

const SINGLE_PAPER_SCHEMA = { type: 'object', properties: PAPER_FIELDS, required: ['title'] };

const CITING_SCHEMA = {
  type: 'object',
  properties: {
    citingPapers: {
      type: 'array',
      items: { type: 'object', properties: PAPER_FIELDS, required: ['title'] },
    },
  },
  required: ['citingPapers'],
};

const RESOURCES_SCHEMA = {
  type: 'object',
  properties: {
    blogTitle: { type: 'string' },
    blogContent: { type: 'string' },
    slides: {
      type: 'array',
      items: {
        type: 'object',
        properties: { title: { type: 'string' }, points: { type: 'array', items: { type: 'string' } } },
        required: ['title', 'points'],
      },
    },
    audioScript: { type: 'string' },
    quiz: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          question: { type: 'string' },
          options: { type: 'array', items: { type: 'string' } },
          correctAnswer: { type: 'integer' },
          explanation: { type: 'string' },
        },
        required: ['question', 'options', 'correctAnswer', 'explanation'],
      },
    },
    flashCards: {
      type: 'array',
      items: {
        type: 'object',
        properties: { front: { type: 'string' }, back: { type: 'string' } },
        required: ['front', 'back'],
      },
    },
  },
  required: ['blogTitle', 'blogContent', 'slides', 'audioScript', 'quiz', 'flashCards'],
};

const toPaper = (raw: any, id: string): Paper => ({
  id,
  title: raw.title,
  year: raw.year ?? 'Unknown',
  authors: raw.authors ?? [],
  summary: raw.summary ?? '',
  citationCount: raw.citationCount,
  status: 'discovered',
});

// --- Discovery (google_search) ---------------------------------------------
/**
 * How many publications one search asks for.
 *
 * This is a single grounded generation: the model searches, reads and writes
 * every paper's metadata in one response. Asking for more than it can do well
 * does not fail — it degrades, returning invented years and merged titles toward
 * the tail, which is exactly the kind of confident wrongness the citation rules
 * in this codebase exist to prevent.
 *
 * Twenty is comfortably within that. Beyond about fifty the answer stops being
 * trustworthy regardless of what is asked, so the ceiling is enforced rather
 * than advisory. Getting a prolific researcher's *whole* output needs
 * pagination — several calls accumulating into one library — not a bigger number
 * here.
 *
 * Read at call time, so it can be changed without a restart.
 */
export const scholarPaperLimit = (requested?: number): number => {
  const fallback = Number(process.env.SCHOLAR_PAPER_LIMIT || 20);
  const wanted = Number.isFinite(requested) && requested! > 0 ? requested! : fallback;
  return Math.min(Math.max(Math.floor(wanted), 1), 50);
};

export const searchScholarAndPapers = async (
  scholarName: string,
  paperLimit?: number
): Promise<{ name: string; affiliation: string; topics: string[]; papers: Paper[] }> => {
  const isUrl = /http|www\.|scholar\.google/i.test(scholarName);
  const limit = scholarPaperLimit(paperLimit);
  const input = isUrl
    ? `Use Google Search to open and analyse this scholar profile URL: "${scholarName}".
       Return the scholar's full personal name exactly as it appears on the profile — a
       person's name, never a URL, username, or ID. Also return their affiliation, research
       topics, and up to ${limit} of their most significant publications with title, year,
       authors, citation count, and a short summary. Prefer their most cited and most
       representative work. Only include publications you can actually verify; returning
       fewer accurate entries is better than padding the list.`
    : `Search for the scholar "${scholarName}". Return their full name as normally written,
       their affiliation, research topics, and up to ${limit} of their most significant
       papers with title, year, authors, approximate citation count, and a two-sentence
       summary each. Prefer their most cited and most representative work. Only include
       publications you can actually verify; returning fewer accurate entries is better
       than padding the list.`;

  // Re-throws by design: the workspace surfaces this failure to the user.
  const interaction = await ask({ input, schema: SCHOLAR_SCHEMA, tools: [googleSearchTool()] });
  const data = extractJson<any>(interaction, {});
  return {
    // Falls back to the query, but never to a raw URL — that becomes the profile title.
    name: data.name || (isUrl ? '' : scholarName),
    affiliation: data.affiliation || 'Unknown Affiliation',
    topics: data.topics || [],
    papers: (data.papers || [])
      .slice(0, limit)
      .map((p: any, i: number) => toPaper(p, `paper-${i}-${Date.now()}`)),
  };
};

export const findSinglePaper = async (query: string): Promise<Paper | null> => {
  try {
    const interaction = await ask({
      input: `Find the research paper best matching: "${query}". Use Google Search for accurate details.`,
      schema: SINGLE_PAPER_SCHEMA,
      tools: [googleSearchTool()],
    });
    const data = extractJson<any>(interaction, {});
    return data?.title ? toPaper(data, `paper-manual-${Date.now()}`) : null;
  } catch (error) {
    console.error('Error finding single paper:', error);
    return null;
  }
};

export const findCitingPapers = async (paperTitle: string, authors: string[]): Promise<Paper[]> => {
  try {
    const interaction = await ask({
      input: `Find 5-8 significant research papers that cite "${paperTitle}" by ${authors.join(', ')}.
              For each, explain in one sentence how it relates to the cited work.`,
      schema: CITING_SCHEMA,
      tools: [googleSearchTool()],
    });
    const data = extractJson<any>(interaction, { citingPapers: [] });
    return (data.citingPapers || []).map((p: any, i: number) => toPaper(p, `citation-${i}-${Date.now()}`));
  } catch (error) {
    console.error('Error finding citations:', error);
    return [];
  }
};

// --- Generation -------------------------------------------------------------
export interface GeneratedResources {
  blogTitle: string;
  blogContent: string;
  slides: Slide[];
  quiz: QuizQuestion[];
  flashCards: FlashCard[];
  audioScript: string;
}

const FAILED_RESOURCES: GeneratedResources = {
  blogTitle: 'Generation Failed',
  blogContent: 'We could not generate content for this paper. Please try again later.',
  slides: [],
  quiz: [],
  flashCards: [],
  audioScript: '',
};

/**
 * Grounding is mutually exclusive (spike finding F2/O1): File Search composes with
 * neither Google Search nor URL Context. Preference order is the indexed corpus,
 * then the paper's own URL, then live search.
 */
/**
 * Two stages, deliberately.
 *
 * Grounding tools and structured output do not compose: File Search injects
 * citation markers like `[3.5]` into the response, and that pass corrupts the
 * `[` that opens a JSON array, so single-call generation reliably produces
 * malformed JSON at the first array. Stage one gathers grounded notes as free
 * prose; stage two structures those notes with no tools attached, where
 * response_format is honoured cleanly.
 *
 * Grounding is also mutually exclusive (spike finding F2/O1): File Search
 * composes with neither Google Search nor URL Context. Preference order is the
 * indexed corpus, then the paper's own URL, then live search.
 */
const gatherNotes = async (
  paper: Paper,
  opts: { storeName?: string; sourceUrl?: string; knownText?: string }
): Promise<string> => {
  let tools: Tool[];
  let grounding: string;

  // A non-paper source was read when it was added — a transcript, a page's
  // text. Re-reading it would cost a second watch or fetch for nothing.
  if (opts.knownText && opts.knownText.length > 200) return opts.knownText;

  if (opts.storeName && paper.fileSearchDocName) {
    tools = [fileSearchTool([opts.storeName])];
    grounding = 'Use file search to read the indexed full text of this paper.';
  } else if (opts.sourceUrl) {
    tools = [urlContextTool()];
    grounding = `Read the paper at ${opts.sourceUrl}.`;
  } else {
    tools = [googleSearchTool()];
    grounding = 'Use Google Search to find the abstract, key findings, and methodology.';
  }

  const interaction = await ask({
    input: `${grounding}

Paper: ${paper.title}
Authors: ${paper.authors.join(', ')}
Known summary: ${paper.summary}

Write detailed research notes in plain prose covering:
- What problem the work addresses and why it matters
- The method and architecture, with specifics
- Key quantitative results
- Five important technical terms with definitions
- Five factual points precise enough to build quiz questions from

Prose only. Do not use JSON, bullet syntax, or code blocks.`,
    tools,
  });

  return extractText(interaction);
};

export const generatePaperResources = async (
  paper: Paper,
  opts: { storeName?: string; sourceUrl?: string; knownText?: string } = {}
): Promise<GeneratedResources> => {
  try {
    const notes = await gatherNotes(paper, opts);

    // Stage two: no tools, so response_format is applied to clean text.
    const interaction = await ask({
      input: `You are an expert research communicator and educator.

Turn these research notes into an educational module.

Paper: ${paper.title}
Authors: ${paper.authors.join(', ')}

NOTES:
${notes || paper.summary}

Requirements:
1. Blog post: engaging, accessible, markdown, under 500 words, covering what they did, how, and why it matters.
2. Slides: 4-6 slides, each with a title and 3-4 bullet points.
3. Audio script: a natural ~50 word podcast intro.
4. Quiz: exactly 5 multiple-choice questions, 4 options each, with the correct index and an explanation.
5. Flashcards: exactly 5 covering key terms, concepts, or findings.

Write plain prose in every field. Do not include bracketed citation markers.`,
      schema: RESOURCES_SCHEMA,
    });

    const data = extractJson<Partial<GeneratedResources>>(interaction, {});
    if (!data.blogContent) return FAILED_RESOURCES;
    return {
      blogTitle: data.blogTitle || `Blog: ${paper.title}`,
      blogContent: data.blogContent,
      slides: data.slides || [],
      quiz: data.quiz || [],
      flashCards: data.flashCards || [],
      audioScript: data.audioScript || paper.summary,
    };
  } catch (error) {
    // Returns a placeholder rather than throwing so one bad paper cannot abort a run.
    console.error('Error generating resources:', error);
    return FAILED_RESOURCES;
  }
};

// --- Media (generateContent; TTS is unreachable via Interactions, finding R8) ---
export interface MediaBlob {
  data: Buffer;
  mime: string;
}

export const generateAudio = async (
  text: string,
  voiceName = 'Kore'
): Promise<MediaBlob | undefined> => {
  try {
    const response = await retryWithBackoff(() =>
      ai().models.generateContent({
        model: MODELS.tts,
        contents: [{ parts: [{ text }] }],
        config: {
          responseModalities: ['AUDIO' as any],
          speechConfig: { voiceConfig: { prebuiltVoiceConfig: { voiceName } } },
        },
      })
    );
    const inline = response.candidates?.[0]?.content?.parts?.[0]?.inlineData;
    if (!inline?.data) return undefined;
    return {
      data: Buffer.from(inline.data, 'base64'),
      // Headerless 24kHz mono PCM, confirmed by the spike (Q4a).
      mime: inline.mimeType || 'audio/l16; rate=24000; channels=1',
    };
  } catch (e) {
    console.error('Error generating audio:', e);
    return undefined;
  }
};

export const generateIllustration = async (
  title: string,
  summary: string
): Promise<MediaBlob | undefined> => {
  try {
    const response = await retryWithBackoff(() =>
      ai().models.generateContent({
        model: MODELS.image,
        contents: {
          parts: [
            {
              text: `Create a detailed, abstract, scientific illustration for a research paper titled "${title}".
                     Summary: ${summary}.
                     Style: modern digital art, clean, isometric, data visualization aesthetic, colourful but professional.`,
            },
          ],
        },
        config: { imageConfig: { aspectRatio: '16:9' } },
      })
    );
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData?.data) {
        return {
          data: Buffer.from(part.inlineData.data, 'base64'),
          // The model returns JPEG despite the app historically assuming PNG (finding R11).
          mime: part.inlineData.mimeType || 'image/jpeg',
        };
      }
    }
    return undefined;
  } catch (error) {
    console.error('Error generating illustration:', error);
    return undefined;
  }
};
